development:
  adapter: postgresql
  encoding: unicode
  database: ggfilter_development
  pool: 5
  username: factorio_mods
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ggfilter_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: factorio_mods
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ggfilter_production
  pool: 5
  username: factorio_mods
  password:
