# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88bc2a5eaad8a6aa7e76ead460a405b02c8e4098faa33a22e525eb1aac972d641a644ad7ce318065c410bd4f9e37384224bcb9e16baf682723696c83afa1041

test:
  secret_key_base: 50e447eb5c95afd9bf7d377887b526279f987c066a1665dc7cd8ab91ff62dff9abc737a23290653e1e08567f6b0ff41acce3afda17d11276f53a06e4754ef7b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
